### ISSUE TITLE
'Microk8s.enable Kubeflow' replies "Kubeflow is already enabled" with missing services

### ISSUE THREAD

**Issue by RFMVasconcelos** [ubuntu/microk8s#1312] opened 2020-06-15 09:27 UTC
When 'microk8s.enable kubeflow' fails to launch all the services, or is in a state with missing services, 'microk8s.enable kubeflow' states that Kubeflow is enabled.

There should be some kind of recovery mechanism, where this command checks the status of the Kubeflow services and restarts missing ones - (e.g. 7/30 pods running).

Example:
![unstable3](https://user-images.githubusercontent.com/27001378/84640643-ddd07900-aef1-11ea-8f22-5fde976e994b.png)

Under these circumstances, the user is forced to disable kubeflow and enable again, which takes a lot time.

**Comment by knkski** [comment] 2020-07-28 19:16
@RFMVasconcelos: Closing this as a duplicate of #1397, feel free to reopen if that's wrong.

**Closed by knkski** 2020-07-28 19:16 UTC
