### ISSUE TITLE
Cluster dropping nodes 1/2 days after creating.

### ISSUE THREAD

**Issue by golgotow** [ubuntu/microk8s#1728] opened 2020-11-11 08:22 UTC
Hello,

Cluster dropping nodes 1/2 days after creating. Attaching inspect from still working node, and from a [node] that does not work.

`root@msi55:~# kubectl get nodes
NAME       STATUS     ROLES    AGE   VERSION
brixone    NotReady   <none>   24h   v1.19.2-34+1b3fa60b402c1c
corosync   Ready      <none>   24h   v1.19.2-34+1b3fa60b402c1c
msi55      Ready      <none>   38h   v1.19.2-34+1b3fa60b402c1c
`
`root@brixone:~# microk8s inspect
Inspecting Certificates
Inspecting services
  Service snap.microk8s.daemon-cluster-agent is running
  Service snap.microk8s.daemon-containerd is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
  Service snap.microk8s.daemon-apiserver-kicker is running
  Service snap.microk8s.daemon-proxy is running
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Copy service arguments to the final report tarball
Inspecting AppArmor configuration
Gathering system information
  Copy processes list to the final report tarball
  Copy snap list to the final report tarball
  Copy VM name (or none) to the final report tarball
  Copy disk usage information to the final report tarball
  Copy memory usage information to the final report tarball
  Copy server uptime to the final report tarball
  Copy current linux distribution to the final report tarball
  Copy openSSL information to the final report tarball
  Copy network configuration to the final report tarball
Inspecting kubernetes cluster
  Inspect kubernetes cluster

Building the report tarball
  Report tarball is at /var/snap/microk8s/1769/inspection-report-20201111_092150.tar.gz
`

Best Regards

**Comment by golgotow** [comment] 2020-11-11 08:23
[inspection-report-20201111_085901-BROKEN.tar.gz](https://github.com/ubuntu/microk8s/files/5522768/inspection-report-20201111_085901-BROKEN.tar.gz)
[inspection-report-20201111_085912-WORK.tar.gz](https://github.com/ubuntu/microk8s/files/5522769/inspection-report-20201111_085912-WORK.tar.gz)

**Comment by balchua** [comment] 2020-11-11 22:53
Hi
I see this in the logs of the broken node
```
Nov 11 08:53:48 brixone systemd[1]: snap.microk8s.daemon-apiserver.service: Main process exited, code=killed, status=11/SEGV
```
Which suggest you are having the same issue as this https://github.com/ubuntu/microk8s/issues/1598

The MicroK8s team will release into `1.19/stable` the fixes for data corruption and segmentation fault.  I suggest to follow the issue there.

**Comment by balchua** [comment] 2020-11-11 22:54
Duplicate of https://github.com/ubuntu/microk8s/issues/1598

**Closed by balchua** 2020-11-11 22:54 UTC
Labels: duplicate
