### ISSUE TITLE
Can't delete a pod -  hanging in Terminating state

### ISSUE THREAD

**Issue by khteh** [ubuntu/microk8s#238] opened 2018-12-11 03:09 UTC
Please run `microk8s.inspect` and attach the generated tarball to this issue.
[inspection-report-20181211_110723.tar.gz](https://github.com/ubuntu/microk8s/files/2665795/inspection-report-20181211_110723.tar.gz)

We appreciate your feedback. Thank you for using microk8s.
The service is deleted but the pod hangs in "Terminating" state:
```
$ k get all
NAME                                          READY   STATUS        RESTARTS   AGE
pod/blazegraph-0                              1/1     Terminating   1          2d17h
pod/default-http-backend-587b7d64b5-c4rzj     1/1     Terminating   7          17d
pod/default-http-backend-587b7d64b5-f95l9     0/1     Pending       0          132m
pod/mysql-0                                   1/1     Terminating   1          2d17h
pod/nginx-78b4dd8bdd-88tf8                    0/1     Pending       0          132m
pod/nginx-78b4dd8bdd-n622r                    1/1     Terminating   7          7d4h
pod/nginx-ingress-microk8s-controller-b9xcd   1/1     Running       1714       17d
pod/web-0                                     1/1     Terminating   2          2d17h

NAME                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/default-http-backend   ClusterIP   10.152.183.94   <none>        80/TCP              17d
service/kubernetes             ClusterIP   10.152.183.1    <none>        443/TCP             17d
service/svc-blazegraph         ClusterIP   None            <none>        3306/TCP,9999/TCP   2d17h
service/svc-mysql              ClusterIP   None            <none>        3306/TCP,9999/TCP   2d17h

NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/nginx-ingress-microk8s-controller   0         0         0       0            0           <none>          17d

NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/default-http-backend   0/1     1            0           17d
deployment.apps/nginx                  0/1     1            0           7d4h

NAME                                              DESIRED   CURRENT   READY   AGE
replicaset.apps/default-http-backend-587b7d64b5   1         1         0       17d
replicaset.apps/nginx-78b4dd8bdd                  1         1         0       7d4h

NAME                          READY   AGE
statefulset.apps/blazegraph   0/1     2d17h
statefulset.apps/mysql        0/1     2d17h

NAME                                              REFERENCE                TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-pilot   Deployment/istio-pilot   <unknown>/55%   1         1         0          17d
```
```
$ k delete pod web-0
pod "web-0" deleted
error: An error occurred while waiting for the object to be deleted: too old resource version: 1435239 
```
```
$ microk8s.reset
Calling clean_cluster
Cleaning resources in namespace default
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
```

**Comment by ktsakalozos** [comment] 2018-12-11 11:13
Hi @khteh ,

Thank you for opening this issue. Starting from a fresh MicroK8s deployment, could you share the steps to reproduce this issue? please share any yaml manifests you apply.

**Comment by khteh** [comment] 2018-12-11 12:55
Hi @ktsakalozos I just updated the container image in the sts manifest and restart the sts. I didn't touch the cluster for about 3 days before making the minor update to the web-0 manifest today and first time seeing this strange error.

What is worrying is seeing the number of crash-looping count almost in every pod in this short period of deployment on localhost.

**Comment by khteh** [comment] 2018-12-14 00:40
```$ k get all
NAME                                          READY   STATUS        RESTARTS   AGE
pod/blazegraph-0                              1/1     Terminating   1          5d12h
pod/default-http-backend-587b7d64b5-c4rzj     1/1     Terminating   7          20d
pod/mysql-0                                   1/1     Terminating   1          5d12h
pod/nginx-78b4dd8bdd-n622r                    1/1     Terminating   7          9d
pod/nginx-ingress-microk8s-controller-b9xcd   1/1     Terminating   1714       20d
pod/web-0                                     1/1     Terminating   2          5d12h

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.152.183.1   <none>        443/TCP   2d14h

NAME                                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/nginx-ingress-microk8s-controller   0         0         0       0            0           <none>          20d

NAME                                              REFERENCE                TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
horizontalpodautoscaler.autoscaling/istio-pilot   Deployment/istio-pilot   <unknown>/55%   1         1         0          20d
```
```
$ k delete pod --all
pod "blazegraph-0" deleted
pod "default-http-backend-587b7d64b5-c4rzj" deleted
pod "mysql-0" deleted
pod "nginx-78b4dd8bdd-n622r" deleted
pod "nginx-ingress-microk8s-controller-b9xcd" deleted
pod "web-0" deleted
error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)error: An error occurred while waiting for the object to be deleted: too old resource version: 1435971 (1450581)```

**Comment by khteh** [comment] 2018-12-14 00:43
What can I do with this? I have tried `snap [dis|en] microk8s` and how to use `microk8s.reset`?
```$ microk8s.reset
Calling clean_cluster
Cleaning resources in namespace default
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
khteh@khteh-T580:/usr/src/kubernetes/cluster1 2407 $ microk8s.reset pod
Calling clean_cluster
Cleaning resources in namespace default
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
khteh@khteh-T580:/usr/src/kubernetes/cluster1 2408 $ microk8s.reset --help
Calling clean_cluster
Cleaning resources in namespace default
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
khteh@khteh-T580:/usr/src/kubernetes/cluster1 2409 $ microk8s.reset -h
Calling clean_cluster
Cleaning resources in namespace default
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
khteh@khteh-T580:/usr/src/kubernetes/cluster1 2410 $ microk8s.reset --all
Calling clean_cluster
Cleaning resources in namespace default
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
error: at least one resource must be specified to use a selector
```

**Comment by leo1971** [comment] 2019-02-20 02:57
I got this error too, it's because I set desired pod num to 2 in statefulset, but I got only one node can be scheduled. I set the  desired pod num to 1 and it works.

**Comment by TyrionQu** [comment] 2019-03-15 03:19
My setting in statefulset is 1, and it run normally nearly 25 day. Yesterday I found some issues, and restart this pod again, but today it meet this problem, and can't be terminate, and try other stateless pod, which met the same problems:

root@adm01:/home/ubuntu/configure/mcs# kubectl get pods -o wide
NAME                           READY   STATUS              RESTARTS   AGE   IP             NODE    NOMINATED NODE   READINESS GATES
hello-world-696b6b59bd-7dx7s   1/1     Running             0          28d   10.233.64.18   work1   <none>           <none>
hello-world-696b6b59bd-bxfkp   0/1     ContainerCreating   0          40m   <none>         work3   <none>           <none>
hello-world-696b6b59bd-j5pfg   1/1     Running             0          28d   10.233.64.15   work3   <none>           <none>
hello-world-696b6b59bd-mt9nd   1/1     Running             0          28d   10.233.64.17   work3   <none>           <none>
hello-world-696b6b59bd-nthf4   0/1     ContainerCreating   0          40m   <none>         work1   <none>           <none>
hello-world-696b6b59bd-qw7pr   1/1     Terminating         0          28d   10.233.64.16   work2   <none>           <none>
hello-world-696b6b59bd-s9rzh   1/1     Running             0          28d   10.233.64.14   work1   <none>           <none>
hello-world-696b6b59bd-sg2bm   1/1     Terminating         0          28d   10.233.64.19   work2   <none>           <none>
xxx0-0                         2/2     Terminating         0          19h   10.233.64.20   work2   <none>           <none>
xxx1-0                         2/2     Terminating         0          20h   10.233.64.21   work3   <none>           <none>
xxx2-0                         2/2     Terminating         0          17h   10.233.64.22   work2   <none>           <none>

**Comment by khteh** [comment] 2019-07-12 01:33
Still happening with the latest microk8s.

**Comment by ktsakalozos** [comment] 2019-07-12 05:20
> Still happening with the latest microk8s

If this is not fixed by the `--allow-privileged` removal, could you attach please the `microk8s.inspect` tarball.

**Comment by khteh** [comment] 2019-07-12 06:11
I can delete sts and the pods now after removing the obsolete --allow-privileged flag.

**Closed** 2020-01-14 23:19 UTC
