### ISSUE TITLE
dns pod in CrashLoopBackoff

### ISSUE THREAD

**Issue by itsallonetome** [ubuntu/microk8s#568] opened 2019-07-30 11:03 UTC
Please run `microk8s.inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

New VM with Ubuntu 16.04.  `apt-get update` && `apt-get --with-new-pkgs --autoremove upgrade`.

```
sudo snap install microk8s --classic
sudo iptables -P FORWARD ACCEPT
microk8s.enable dns
```
```
microk8s.kubectl get all -n all --all-namespaces
NAMESPACE     NAME                          READY   STATUS             RESTARTS   AGE
kube-system   pod/coredns-f7867546d-c4n9s   0/1     CrashLoopBackOff   7          6m10s


NAMESPACE     NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP                  22m
kube-system   service/kube-dns     ClusterIP   10.152.183.10   <none>        53/UDP,53/TCP,9153/TCP   6m10s


NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/1     1            0           6m10s

NAMESPACE     NAME                                DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-f7867546d   1         1         0       6m10s
````

**Comment by itsallonetome** [comment] 2019-07-30 11:03
[inspection-report-20190730_105645.tar.gz](https://github.com/ubuntu/microk8s/files/3446468/inspection-report-20190730_105645.tar.gz)

**Comment by ktsakalozos** [comment] 2019-07-30 11:11
Hi @itsallonetome this is a duplicate of https://github.com/ubuntu/microk8s/issues/533. The fix is already on candidate (`sudo snap install microk8s --classic --channel=candidate`) and should be released to stable this week.

**Closed by ktsakalozos** 2019-07-30 11:11 UTC
