### ISSUE TITLE
Unable to install and run kubeflow

### ISSUE THREAD

**Issue by leeadh** [ubuntu/microk8s#2716] opened 2021-11-07 07:36 UTC
I cant seem to be able to access mkubeflow through microk8. I followed this guide here https://iamageek.medium.com/install-kubeflow-in-10-steps-on-macos-96d7dda9612 and was unable to access it when I did a and here https://ubuntu.com/tutorials/deploy-kubeflow-ubuntu-windows-mac#5-access-the-kubeflow-dashboard

I am using `sudo snap install microk8s --classic --channel=1.18`

After ensuring that the kubeflow is installed, I did the below

```
ubuntu@kubeflow:~$ sudo -- sh -c "echo '10.64.140.43\t10.64.140.43.xip.io' >> /etc/hosts"
ubuntu@kubeflow:~$ sudo iptables -P FORWARD ACCEPT
ubuntu@kubeflow:~$ exit
ssh -i kubeflow -D9999 ubuntu@192.168.64.4
```

But I keep getting an Access to 10.64.140.43.xip.io was forbidden when I try to access via the browser ( I already set the SOCKS proxy). 

Seems the documentation is very bad or not clear at all and didn't improve since June last year : https://github.com/ubuntu/microk8s/issues/1243#issuecomment-635429958

![image](https://user-images.githubusercontent.com/15122358/140637945-04581c25-ddfa-4209-a482-c241769e2bfc.png)

**Comment by DomFleischmann** [comment] 2021-11-12 09:04
Duplicate of [this](https://github.com/canonical/bundle-kubeflow/issues/406)

**Closed by DomFleischmann** 2021-11-12 09:04 UTC
