### ISSUE TITLE
Problems installing on MacOS

### ISSUE THREAD

**Issue by oluies** [ubuntu/microk8s#1886] opened 2021-01-11 20:03 UTC
Please run `microk8s inspect` and attach the generated tarball to this issue.

We appreciate your feedback. Thank you for using microk8s.

2021-01-11 20:57:50 +0100

/usr/local/Cellar/microk8s/2.0.2/libexec/bin/pip
install
-v
--no-deps
--no-binary
:all:
--no-user
--ignore-installed
/private/tmp/microk8s--jsonschema-20210111-11202-wclphl/jsonschema-2.5.1

Using pip 20.3.3 from /usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip (python 3.9)
Non-user install by explicit request
Created temporary directory: /private/tmp/pip-ephem-wheel-cache-biacj4o1
Created temporary directory: /private/tmp/pip-req-tracker-ajo2rw5_
Initialized build tracking at /private/tmp/pip-req-tracker-ajo2rw5_
Created build tracker: /private/tmp/pip-req-tracker-ajo2rw5_
Entered build tracker: /private/tmp/pip-req-tracker-ajo2rw5_
Created temporary directory: /private/tmp/pip-install-ankm_qc5
Processing /private/tmp/microk8s--jsonschema-20210111-11202-wclphl/jsonschema-2.5.1
  Created temporary directory: /private/tmp/pip-req-build-fpi8iqov
  Added file:///private/tmp/microk8s--jsonschema-20210111-11202-wclphl/jsonschema-2.5.1 to build tracker '/private/tmp/pip-req-tracker-ajo2rw5_'
    Running setup.py (path:/private/tmp/pip-req-build-fpi8iqov/setup.py) egg_info for package from file:///private/tmp/microk8s--jsonschema-20210111-11202-wclphl/jsonschema-2.5.1
    Created temporary directory: /private/tmp/pip-pip-egg-info-gl8rkq1w
    Running command python setup.py egg_info
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-wheel-yo9ve7xn/vcversioner_ca95fe2b12834082a7f496897e4f1314/setup.py'"'"'; __file__='"'"'/private/tmp/pip-wheel-yo9ve7xn/vcversioner_ca95fe2b12834082a7f496897e4f1314/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/tmp/pip-wheel-eup9dxtp
           cwd: /private/tmp/pip-wheel-yo9ve7xn/vcversioner_ca95fe2b12834082a7f496897e4f1314/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for vcversioner
    ERROR: Failed to build one or more wheels
    Traceback (most recent call last):
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/usr/local/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmp6xpk0dsn', '--quiet', 'vcversioner']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-fpi8iqov/setup.py", line 30, in <module>
        setup(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1061, in obtain
        return installer(requirement)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/usr/local/Cellar/microk8s/2.0.2/libexec/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/private/tmp/tmp6xpk0dsn', '--quiet', 'vcversioner']' returned non-zero exit status 1.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", line 169, in _merge_into_criterion
    name = self._p.identify(requirement)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 60, in identify
    return dependency.name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py", line 41, in name
    return self.candidate.name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 188, in name
    return self.project_name
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 182, in project_name
    self._name = canonicalize_name(self.dist.project_name)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 88, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 41, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/usr/local/Cellar/microk8s/2.0.2/libexec/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 240, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///private/tmp/microk8s--jsonschema-20210111-11202-wclphl/jsonschema-2.5.1 from build tracker '/private/tmp/pip-req-tracker-ajo2rw5_'
Removed build tracker: '/private/tmp/pip-req-tracker-ajo2rw5_'

HOMEBREW_VERSION: 2.7.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: a7d7b703696d6d01eda4d4716257ccb0dbe3ab5a
Last commit: 9 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 190b6fb305232a6439856b8ec40711f18f77886a
Core tap last commit: 81 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: atom
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit haswell
Clang: 12.0 build 1200
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 14.0.1
macOS: 11.2-x86_64
CLT: 12.3.0.0.1.1607026830
Xcode: N/A

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local/opt/tcl-tk:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/tcl-tk/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/tcl-tk/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.9/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by joedborg** [comment] 2021-01-11 20:11
Duplicate of https://github.com/ubuntu/microk8s/issues/1882

**Closed by joedborg** 2021-01-11 20:11 UTC
