### ISSUE TITLE
microk8s no longer survives a reboot

### ISSUE THREAD

**Issue by wallyworld** [ubuntu/microk8s#149] opened 2018-10-24 19:53 UTC
It seems that recently, microk8s no longer survives a reboot of the machine.

2 of the snap services do not start.
Running snap restart microk8s fixes it.

[inspection-report-20181025_055133.tar.gz](https://github.com/ubuntu/microk8s/files/2512096/inspection-report-20181025_055133.tar.gz)

$ microk8s.inspect 
Inspecting services
  Service snap.microk8s.daemon-docker is running
 FAIL:  Service snap.microk8s.daemon-apiserver is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-apiserver
 FAIL:  Service snap.microk8s.daemon-proxy is not running
For more details look at: sudo journalctl -u snap.microk8s.daemon-proxy
  Service snap.microk8s.daemon-kubelet is running
  Service snap.microk8s.daemon-scheduler is running
  Service snap.microk8s.daemon-controller-manager is running
  Service snap.microk8s.daemon-etcd is running

**Comment by ktsakalozos** [comment] 2018-10-25 05:58
Thank you for reporting this @wallyworld 

Both services are failing with:

`error: unable to find suitable network address.error='no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"'. Try to set the AdvertiseAddress directly or provide a valid BindAddress to fix this`

`unable to create proxier: failed to select a host interface: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"`

This is similar to what was reported some time ago for deploying on multipass. 

We will have a fix for this soon.

**Closed** 2018-11-01 13:21 UTC

**Comment by ktsakalozos** [comment] 2018-11-01 16:31
@wallyworld the fix is released on edge. However since I was not able to reproduce the problem would it be possible for you to give it a try and see if we fixed it? Many thanks.

`snap install microk8s --edge --classic`
