### ISSUE TITLE
stuck on operator pods to come up

### ISSUE THREAD

**Issue by bidva** [ubuntu/microk8s#1071] opened 2020-03-28 04:39 UTC
Sorry I'm pretty new on microk8s, I tried to run kubeflow on my mac machine not sure if I missed something or it's a bug
here you can find the tarball of inspection
[inspection-report-20200327_213634.tar.gz](https://github.com/ubuntu/microk8s/files/4396631/inspection-report-20200327_213634.tar.gz)

I followed [link](https://www.kubeflow.org/docs/other-guides/virtual-dev/getting-started-multipass/
) 
steps to reproduce:
lunch multipass by
`multipass launch --name test -c 6 -m 12G --disk 80G`
then running `microk8s.enable kubeflow`

result: the process will be stuck on this line 
`Waited 3570s for operator pods to come up, 1 remaining.`

not sure what should I do and what is this pod and why it's not coming up

I really appreciate any help

**Comment by cmxela** [comment] 2020-03-30 14:18
I'm getting the same/similar problem enabling kubeflow on microk8s v1.8.0/edge running on ubuntu 19.10. the process never ends and the number of operator pods waiting to come up is going up and down.

I have enabled kubeflow using the `KUBEFLOW_DEBUG=true` and in the attached file is the output:

[kubeflow_enable.txt](https://github.com/ubuntu/microk8s/files/4403341/kubeflow_enable.txt)

I have run `microk8s inspect` after cancelling the enable with `ctrl+C` and here is the tarball file

[inspection-report-20200330_161444.tar.gz](https://github.com/ubuntu/microk8s/files/4403369/inspection-report-20200330_161444.tar.gz)

**Comment by ereil** [comment] 2020-03-31 08:28
Hi, same here.
fresh Ubuntu 18.04.4 installation, nvidia cuda and driver 418.67 .deb package, docker ce 18.06.1, nvidia-docker2
Just done this:
```
sudo snap install microk8s --classic
sudo microk8s.status --wait-ready
sudo usermod -a -G microk8s $USER
su - $USER
sudo microk8s.enable dns storage dashboard
sudo snap alias microk8s.kubectl kubectl
sudo chown -R $USER ~/.kube
microk8s.kubectl config view --raw > $HOME/.kube/config
microk8s.enable gpu
sudo nano /etc/docker/daemon.json
sudo iptables -P FORWARD ACCEPT
sudo apt-get install iptables-persistent
sudo microk8s.inspect
microk8s.enable kubeflow
```
remaining operator pods goes up and down
![Bildschirmfoto vom 2020-03-31 10-25-03](https://user-images.githubusercontent.com/62931301/78004269-28eadf00-733a-11ea-9602-a7f4319433ee.png)

**Comment by ktsakalozos** [comment] 2020-03-31 09:15
@ereil @bidva @cmxela thank you for reporting this. Could you please try the following workaround until we properly fix this issue? While the kubeflow pods are coming up open a second terminal and disable RBAC with `sudo microk8s.disable rbac`.

@knkski in the apiserver logs I see (with `journalctl -fu snap.microk8s.daemon-apiserver`):
```
r 31 08:01:27 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: W0331 08:01:27.483248    5355 dispatcher.go:181] Failed calling webhook, failing closed webhook.cert-manager.io: failed calling webhook "webhook.cert-manager.io": an error on the server ("Internal Server Error: \"/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s\": subjectaccessreviews.authorization.k8s.io is forbidden: User \"system:serviceaccount:kubeflow:cert-manager-webhook\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope") has prevented the request from succeeding
Mar 31 08:04:00 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: E0331 08:04:00.430018    5355 structuredmerge.go:103] [SHOULD NOT HAPPEN] failed to create typed new object of type admissionregistration.k8s.io/v1beta1, Kind=MutatingWebhookConfiguration: errors:
Mar 31 08:04:00 ip-172-31-21-176 microk8s.daemon-apiserver[5355]:   .webhooks: duplicate entries for key [name="mseldondeployment.kb.io"]
Mar 31 08:04:02 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: W0331 08:04:02.552712    5355 dispatcher.go:181] Failed calling webhook, failing closed webhook.cert-manager.io: failed calling webhook "webhook.cert-manager.io": an error on the server ("Internal Server Error: \"/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s\": subjectaccessreviews.authorization.k8s.io is forbidden: User \"system:serviceaccount:kubeflow:cert-manager-webhook\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope") has prevented the request from succeeding
Mar 31 08:06:27 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: E0331 08:06:27.465104    5355 structuredmerge.go:103] [SHOULD NOT HAPPEN] failed to create typed new object of type admissionregistration.k8s.io/v1beta1, Kind=MutatingWebhookConfiguration: errors:
Mar 31 08:06:27 ip-172-31-21-176 microk8s.daemon-apiserver[5355]:   .webhooks: duplicate entries for key [name="mseldondeployment.kb.io"]
Mar 31 08:06:29 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: W0331 08:06:29.981790    5355 dispatcher.go:181] Failed calling webhook, failing closed webhook.cert-manager.io: failed calling webhook "webhook.cert-manager.io": an error on the server ("Internal Server Error: \"/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s\": subjectaccessreviews.authorization.k8s.io is forbidden: User \"system:serviceaccount:kubeflow:cert-manager-webhook\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope") has prevented the request from succeeding
Mar 31 08:09:03 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: E0331 08:09:03.078267    5355 structuredmerge.go:103] [SHOULD NOT HAPPEN] failed to create typed new object of type admissionregistration.k8s.io/v1beta1, Kind=MutatingWebhookConfiguration: errors:
Mar 31 08:09:03 ip-172-31-21-176 microk8s.daemon-apiserver[5355]:   .webhooks: duplicate entries for key [name="mseldondeployment.kb.io"]
Mar 31 08:09:06 ip-172-31-21-176 microk8s.daemon-apiserver[5355]: W0331 08:09:06.188845    5355 dispatcher.go:181] Failed calling webhook, failing closed webhook.cert-manager.io: failed calling webhook "webhook.cert-manager.io": an error on the server ("Internal Server Error: \"/apis/webhook.cert-manager.io/v1beta1/mutations?timeout=30s\": subjectaccessreviews.authorization.k8s.io is forbidden: User \"system:serviceaccount:kubeflow:cert-manager-webhook\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope") has prevented the request from succeeding
```

When adding more logs by editing `/var/snap/microk8s/current/args/kube-apiserver` to add an `-v=7` argument and restarting MicroK8s `sudo systemctl restart snap.microk8s.daemon-apiserver`. We have a better view on the denials:
```
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.255001   32471 httplog.go:90] verb="GET" URI="/apis/batch/v1/jobs?limit=500" latency=1.521498ms resp=200 UserAgent="kube-controller-manager/v1.18.0 (linux/
amd64) kubernetes/9e99141/system:serviceaccount:kube-system:cronjob-controller" srcIP="127.0.0.1:42624":                                                                                                                                     Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.255608   32471 handler.go:153] kube-aggregator: GET "/apis/batch/v1beta1/cronjobs" satisfied by nonGoRestful                          
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.255632   32471 pathrecorder.go:247] kube-aggregator: "/apis/batch/v1beta1/cronjobs" satisfied by prefix /apis/batch/v1beta1/                               
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.255643   32471 handler.go:143] kube-apiserver: GET "/apis/batch/v1beta1/cronjobs" satisfied by gorestful with webservice /apis/batch/v1beta1               Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.256393   32471 httplog.go:90] verb="GET" URI="/apis/batch/v1beta1/cronjobs?limit=500" latency=889.422µs resp=200 UserAgent="kube-controller-manager/v1.18.0
 (linux/amd64) kubernetes/9e99141/system:serviceaccount:kube-system:cronjob-controller" srcIP="127.0.0.1:42624":                                                                                                                             Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.277133   32471 rbac.go:119] RBAC DENY: user "system:serviceaccount:kubeflow:pytorch-operator" groups ["system:serviceaccounts" "system:serviceaccounts:kube
flow" "system:authenticated"] cannot "list" resource "pods" cluster-wide                                                                                                                               
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.277163   32471 authorization.go:73] Forbidden: "/api/v1/pods?limit=500&resourceVersion=0", Reason: ""                                                      Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.277234   32471 httplog.go:90] verb="GET" URI="/api/v1/pods?limit=500&resourceVersion=0" latency=511.121µs resp=403 UserAgent="pytorch-operator.v1/v0.0.0 (l
inux/amd64) kubernetes/$Format/pytorch-operator" srcIP="10.1.83.77:33330":                                                                                                                                                                   Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.277834   32471 rbac.go:119] RBAC DENY: user "system:serviceaccount:kubeflow:pytorch-operator" groups ["system:serviceaccounts" "system:serviceaccounts:kube
flow" "system:authenticated"] cannot "list" resource "services" cluster-wide                                                                                                                                                                 
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.277859   32471 authorization.go:73] Forbidden: "/api/v1/services?limit=500&resourceVersion=0", Reason: ""                                                  Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.277919   32471 httplog.go:90] verb="GET" URI="/api/v1/services?limit=500&resourceVersion=0" latency=188.525µs resp=403 UserAgent="pytorch-operator.v1/v0.0.
0 (linux/amd64) kubernetes/$Format/pytorch-operator" srcIP="10.1.83.77:33330":                                                                                                                                                               
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.278989   32471 rbac.go:119] RBAC DENY: user "system:serviceaccount:kubeflow:pytorch-operator" groups ["system:serviceaccounts" "system:serviceaccounts:kube
flow" "system:authenticated"] cannot "list" resource "pytorchjobs.kubeflow.org" cluster-wide                                                                                                                          
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.279013   32471 authorization.go:73] Forbidden: "/apis/kubeflow.org/v1/pytorchjobs?limit=500&resourceVersion=0", Reason: ""                                 Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.279073   32471 httplog.go:90] verb="GET" URI="/apis/kubeflow.org/v1/pytorchjobs?limit=500&resourceVersion=0" latency=172.032µs resp=403 UserAgent="pytorch-
operator.v1/v0.0.0 (linux/amd64) kubernetes/$Format/kube-batch" srcIP="10.1.83.77:33330":                                                                                                                                                    Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.372122   32471 handler.go:153] kube-aggregator: GET "/api/v1/namespaces/kube-system/endpoints/kube-scheduler" satisfied by nonGoRestful
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.372155   32471 pathrecorder.go:247] kube-aggregator: "/api/v1/namespaces/kube-system/endpoints/kube-scheduler" satisfied by prefix /api/                   Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.372167   32471 handler.go:143] kube-apiserver: GET "/api/v1/namespaces/kube-system/endpoints/kube-scheduler" satisfied by gorestful with webservice /api/v1
Mar 31 08:28:18 ip-172-31-21-176 microk8s.daemon-apiserver[32471]: I0331 08:28:18.373218   32471 httplog.go:90] verb="GET" URI="/api/v1/namespaces/kube-system/endpoints/kube-scheduler?timeout=10s" latency=1.231998ms resp=200 UserAgent="kube-scheduler/v1.18.0 (linux/amd64) kubernetes/9e99141/leader-election" srcIP="127.0.0.1:42432":
```

**Comment by ereil** [comment] 2020-03-31 10:11
@ktsakalozos The workaround is working. Thanks!
Am I right that RBAC after pod initialisation should stay disabled?

**Comment by ktsakalozos** [comment] 2020-03-31 10:16
> Am I right that RBAC after pod initialisation should stay disabled?

Yes please keep it disabled until we fix the issue.

**Comment by ktsakalozos** [comment] 2020-03-31 14:53
@wallyworld are the RBAC denials something Juju should address for on the v1.18 k8s release?

**Comment by knkski** [comment] 2020-04-02 15:07
Closing as fixed by #1080

**Closed by knkski** 2020-04-02 15:07 UTC

**Comment by tlm** [comment] 2020-04-06 21:07
Hey @ktsakalozos, @knkski,

I spent some time looking into this and seeing if Juju was the cause and I don't believe that it is. For my setup it looks as though RBAC is broken in microk8s as the api server is even having a hard time validating the service accounts of the kubelet/node user.

Errors above also fit with pods not starting up.

It would be great to see kubectl describe output from some of the pods that are not starting up to further help narrow the cause down. But I don't believe this is Juju related.

Thanks
Tom

**Comment by ktsakalozos** [comment] 2020-04-07 08:56
Hi @tlm , often rbac failures are due to invalid characters in the hostname (eg capital letters).

Could you share the tarball from `microk8s.inspect` displaying the denials?

**Comment by cbrendanprice** [comment] 2020-08-28 21:19
@ktsakalozos was this issue actually "fixed"? not sure if this problem is more specific to running microk8s within wsl2 (with nested virtualization) but if i enable rbac i am unable to get anything to work properly. however, once rbac is disabled, everything works nominally. happy to provide whatever details you think would be useful.

**Comment by ktsakalozos** [comment] 2020-08-29 05:54
Hi @cbrendanprice,

Could you try installing MicroK8s from the `latest/candidate` channel (`sudo snap install microk8s --classic --channel=latest/candidate`)? Could you also attach the tarball produced by `microk8s.inspect`?
