### ISSUE TITLE
Can't bring up dashboard

### ISSUE THREAD

**Issue by fethomm** [ubuntu/microk8s#1704] opened 2020-11-01 14:58 UTC
I am new to all of Kubernetes, but quite versed in Linux in general. So today for testing purposes I installed ubuntu 20.10 server 64-bit on 2 raspberry pis and installed microk8s on both. All goes well, I can join the leaf to the master.

 What does not work is bringing up the dashboard. The command 'microk8s dashboard-proxy' tells me, the dashboard will be available at https://127.0.0.1:10443 and gives me a token. The browser says: '127.0.0.1 has denied the connection'. I did some reading, but can't get it solved. Help is much appreciated.

[inspection-report-20201101_143714.tar.gz](https://github.com/ubuntu/microk8s/files/5471136/inspection-report-20201101_143714.tar.gz)

**Comment by ktsakalozos** [comment] 2020-11-02 08:50
Duplicate of https://github.com/ubuntu/microk8s/issues/1705

**Closed by ktsakalozos** 2020-11-02 08:50 UTC
