### ISSUE TITLE
Help with jenkins x 3 

### ISSUE THREAD

**Issue by manisabri** [ubuntu/microk8s#1997] opened 2021-02-09 20:27 UTC
Hi

I'm trying to setup jx3 on microk8s with a valid domain name on my laptop with dynamic dns 
I have both microk8s ingress and jx3 ingress controllers and I'm using gitea webhooks but they are not working. Having a guide for jx3 will be extremely useful 

Thank you
Mani

**Comment by balchua** [comment] 2021-02-13 10:55
What error are you getting?  For JenkinsX issues, you may get better help from the jenkins community.

**Comment by manisabri** [comment] 2021-02-14 12:21
The error is  _**x509: certificate is valid for ingress.local, not hook-jx.redacted.com**_ 

I know why I get the error.

I have two ingress controllers _microk8s-ingress_ and _nginx-ingress_ installed by JX.
_microk8s-ingress_ uses **nodePorts** and _nginx-ingress_ uses some ip address issued by **Metallb** 

The problem is that all traffic to *.redacted.com goes to _microk8s-ingress_.

I guess I need to find a way to route some subdomains to the IP address of the _nginx-ingress_. 
Is it doable?

I have put the question to people in JX community but didn't get any answer. They mostly deal with GKE and it seems their on premise guide assumes people have multiple valid IP addresses and can assign different IP addresses to different subdomains. which is not my case. I only have one valid IP address on the modem.

**Comment by balchua** [comment] 2021-02-14 12:40
You can check the nginx ingress class used by jenkins x if you want to use that nginx.  Then annotate your ingress resource with that class.  Its possible that the ingress class is named `nginx`.

For microk8s ingress, it uses "public" as its ingress class.

This [link multiple ingress](
https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/) describes in more details.

**Comment by manisabri** [comment] 2021-02-14 21:30
I managed to get it working by configuring **CoreDNS** to resolve the domain name to the internal IP address.
I'm probably stuck somewhere else but that part is solved at least.

**Comment by balchua** [comment] 2021-03-05 12:15
Will be closing this since it seems like the issue is resolved.  Feel free to open one when you need help. Thanks!

**Closed by balchua** 2021-03-05 12:15 UTC
Labels: Q&A
