### ISSUE TITLE
Can't apply some K8s manifests because of undefined symbol and GLIBC_PRIVATE

### ISSUE THREAD

**Issue by kimwnasptd** [ubuntu/microk8s#4453] opened 2024-03-07 14:27 UTC
#### Summary

I've tried to run the following command in a microK8s 1.29 (snap) and it fails to apply the resources
```bash
$ microk8s.kubectl apply -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd?ref=v0.29.0'
error: failed to run '/snap/microk8s/6539/usr/bin/git fetch --depth=1 https://github.com/intel/intel-device-plugins-for-kubernetes v0.29.0': /usr/lib/git-core/git-remote-https: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE: exit status 128
```

#### What Should Happen Instead?
The above manifests can be installed with the following
```bash
sudo snap install kubectl --classic
sudo microk8s kubectl config view --raw > $HOME/.kube/config
kubectl apply -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd?ref=v0.29.0'
```

Comparing the 2 kubectl versions I see they are identical
```bash
kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2

microk8s.kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```

#### Reproduction Steps

```bash
sudo snap install microk8s --classic --channel=1.29/stable
microk8s.kubectl apply -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd?ref=v0.29.0'
```

**Comment by neoaggelos** [comment] 2024-03-10 08:48
Thanks for reporting @kimwnasptd. This is a duplicate of https://github.com/canonical/microk8s/issues/3988

**Closed as not planned by neoaggelos** 2024-03-10 08:48 UTC
