### ISSUE TITLE
'microk8s.enable kubeflow' fails because of juju 'No controller registered'

### ISSUE THREAD

**Issue by calanchue** [ubuntu/microk8s#1245] opened 2020-05-28 07:26 UTC
[inspection-report-20200528_161553.tar.gz](https://github.com/ubuntu/microk8s/files/4693888/inspection-report-20200528_161553.tar.gz)

running mcirok8s.enable is failed. 

```
$ sudo microk8s.enable kubeflow
Enabling dns...
Enabling storage...
Enabling dashboard...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for DNS and storage plugins to finish setting up
Deploying Kubeflow...
Kubeflow could not be enabled:
ERROR unknown cloud "microk8s", please try "juju update-clouds"

Command '('microk8s-juju.wrapper', 'bootstrap', 'microk8s', 'uk8s')' returned non-zero exit status 1
Failed to enable kubeflow
```

Error message is same as https://github.com/ubuntu/microk8s/issues/943. But problem cause seems different from it.

```
$ sudo microk8s.juju status --debug
ERROR No controllers registered.

Please either create a new controller using "juju bootstrap" or connect to
another controller that you have been given access to using "juju register".
```

how can i solve this?

**Comment by knkski** [comment] 2020-05-28 15:46
Can you post the output from `microk8s.juju list-clouds`?

If you run `microk8s.juju update-clouds`, does that fix it?

**Comment by calanchue** [comment] 2020-05-29 11:07
```
$ sudo microk8s.juju list-clouds
Only clouds with registered credentials are shown.
There are more clouds, use --all to see them.
You can bootstrap a new controller using one of these clouds...

Clouds available on the client:
Cloud      Regions  Default    Type  Credentials  Source    Description
localhost  1        localhost  lxd   0            built-in  LXD Container Hypervisor

$ sudo microk8s.juju update-clouds
Fetching latest public cloud list...
This client's list of public clouds is up to date, see `juju clouds --client-only`.
```
Actually i did updating clouds before writing this issue. Becuase of that,`list-clouds` say it is already up to date. I saw something is going on when i tried `update-clouds`. But as you can see above, There were no change when i do `microk8s.enable kubeflow`

**Comment by junhwi** [comment] 2020-06-10 05:55
@calanchue Have you tried it without `sudo`?
I got the same problem and adding permissions solved it.
```sh
$ sudo usermod -a -G microk8s $USER
$ microk8s juju list-clouds
```

**Comment by knkski** [comment] 2020-07-27 18:45
@calanchue: I'm going to close this as a duplicate of #1396, as it looks like this issue is related to permissions, as in that ticket.

**Closed by knkski** 2020-07-27 18:45 UTC
