### ISSUE TITLE
Microk8s clustering (join command) error caused by missing SSL Module

### ISSUE THREAD

**Issue by CalvinHartwell** [ubuntu/microk8s#720] opened 2019-10-13 23:06 UTC
Hi all, 

Microk8s v1.16.0 rev 921 doesn't seem to start on arm64. The main issue I am seeing is related to a missing SSL library within the snap: 

```
Oct 13 22:59:55 battleship systemd[1]: Started Service for snap application microk8s.daemon-cluster-agent.
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]: Traceback (most recent call last):
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/bin/gunicorn3", line 9, in <module>
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     load_entry_point('gunicorn==19.4.5', 'console_scripts', 'gunicorn')()
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     return get_distribution(dist).load_entry_point(group, name)
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     return ep.load()
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     return self.resolve()
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 10, in <module>
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     from gunicorn.app.base import Application
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 14, in <module>
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     from gunicorn.config import Config, get_default_config_file
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3/dist-packages/gunicorn/config.py", line 17, in <module>
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     import ssl
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:   File "/snap/microk8s/921/usr/lib/python3.5/ssl.py", line 98, in <module>
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]:     import _ssl             # if we can't import it, let the error propagate
Oct 13 22:59:57 battleship microk8s.daemon-cluster-agent[20195]: ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

I have attached the inspection report. 

[inspection-report-20191013_230126.tar.gz](https://github.com/ubuntu/microk8s/files/3722566/inspection-report-20191013_230126.tar.gz)

Cheers,

- Calvin

**Comment by balchua** [comment] 2019-10-14 06:48
I think there's already a fix for this ssl thingy.  Can you try the `1.16/edge` release?

**Comment by CalvinHartwell** [comment] 2019-10-14 11:00
> I think there's already a fix for this ssl thingy. Can you try the `1.16/edge` release?

> Name      Version  Rev    Tracking   Publisher   Notes
> core      16-2.42  7920   stable     canonical✓  core
> lxd       3.18     12187  stable/…   canonical✓  -
> microk8s  v1.16.1  954    1.16/edge  canonical✓  classic
> 

```
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]: Traceback (most recent call last):
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/bin/gunicorn3", line 9, in <module>
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     load_entry_point('gunicorn==19.4.5', 'console_scripts', 'gunicorn')()
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     return get_distribution(dist).load_entry_point(group, name)
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     return ep.load()
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     return self.resolve()
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     module = __import__(self.module_name, fromlist=['__name__'], level=0)
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 10, in <module>
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     from gunicorn.app.base import Application
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 14, in <module>
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     from gunicorn.config import Config, get_default_config_file
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3/dist-packages/gunicorn/config.py", line 17, in <module>
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     import ssl
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:   File "/snap/microk8s/954/usr/lib/python3.5/ssl.py", line 98, in <module>
Oct 14 10:58:45 battleship microk8s.daemon-cluster-agent[10284]:     import _ssl             # if we can't import it, let the error propagate

```

**Comment by balchua** [comment] 2019-10-14 12:07
@ktsakalozos @DomFleischmann It looks like we need to add the same fix for the micrk8s.join command like mentioned in this PR https://github.com/ubuntu/microk8s/pull/703

**Comment by ktsakalozos** [comment] 2019-10-14 13:15
I believe the problem is with definitions like this one: https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-join.wrapper#L6
```
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu"
```

Obviously `x86_64` does not apply for arm. Trying a fix now.

**Comment by CalvinHartwell** [comment] 2019-10-14 17:09
Thanks @ktsakalozos as soon as you are ready to test, let me know.

**Closed** 2019-10-15 05:09 UTC

**Comment by CalvinHartwell** [comment] 2019-10-15 14:23
Thanks for the help, fix is confirmed to work!
