### ISSUE TITLE
Unable to login into KubeFlow after the addon is enabled

### ISSUE THREAD

**Issue by pisymbol** [ubuntu/microk8s#817] opened 2019-11-21 18:13 UTC
[inspection-report-20191121_130543.tar.gz](https://github.com/ubuntu/microk8s/files/3876068/inspection-report-20191121_130543.tar.gz)

Installed microk8s on a 32-core/64GB workstation running 18.04LTS latest. The snap install and addon enablement went fine:

snap install microk8s --classic
microk8s.enable registry dns rbac storage knative kubeflow istio
...all worked...

KubeFlow is at 0.6.0-rc0

At the end of install, I see that KubeFlow is up and running (all objects in *kubeflow* namespace are RUNNING).

However, I have no way to login. The best I could come up with is:

$ microk8s.kubectl port-forward svc/ambassador -n kubeflow 8080:80

Which does seem to trigger Ambassador and redirect me to the https://localhost:8080/kflogin page. But at that point the SSL connection fails with either:

SSL_ERROR_RX_RECORD_TOO_LONG  (Firefox)
ERR_SSL_PROTOCOL_ERROR (Chrome)

I assume a self-signed certificate is installed via the microk8s addon process.

Again, the dashboard is definitely up since I can port-forward to it directly but then all links off of that page are 404 (I suspects the redirects are screwed up because of the direct connection to 8082). Help!

**Comment by pisymbol** [comment] 2019-11-21 19:05
Update: One little tidbit I forgot to mention is that the original enablement of KubeFlow timed out as my pods were initializing (it just takes TIME for me to download the images and the pods to come up to a RUNNING state).

My guess is the ingress it normally creates didn't happen because of it. But that seems still like a bug.

**Comment by tshauck** [comment] 2019-11-27 03:31
Were you able to manually fix this then? I'm getting the same error and from what I can tell everything was able to get started w/o a timeout, though I still get `SSL_ERROR_RX_RECORD_TOO_LONG`.

**Comment by pisymbol** [comment] 2019-11-27 15:23
> Were you able to manually fix this then? I'm getting the same error and from what I can tell everything was able to get started w/o a timeout, though I still get `SSL_ERROR_RX_RECORD_TOO_LONG`.

There was A LOT of manual intervention to get this all to work right.

**Comment by ktsakalozos** [comment] 2019-11-27 15:33
I am re-opening this since it seems there more to be discussed.

The issue was closed automatically by the merge of the referenced PR.

**Comment by charlesa101** [comment] 2019-11-28 00:47
yeah I am having the same error as well

**Comment by knkski** [comment] 2019-11-28 19:22
@charlesa101, @tshauck: If the deploy process timed out previously, you won't have the necessary patch to the Ingress for Ambassador. Can you see if `microk8s.kubectl get -n kubeflow ingress -oyaml` shows a `tls` section? A missing `tls` section will be responsible for the `SSL_ERROR_RX_RECORD_TOO_LONG` error. 

If not, can you try one of these:

1. Making sure you're on the latest microk8s snap and doing `microk8s.disable kubeflow && microk8s.enable kubeflow`? That removes the timeout, so should properly patch in the `tls` section

2. Manually patch in the `tls` section by passing this in to `microk8s.kubectl apply`:
    
        {"kind": "Ingress", "apiVersion": "extensions/v1beta1", "metadata": {"name": "ambassador", "namespace": "kubeflow"}, "spec": {"tls": [{"hosts": ["localhost"], "secretName": "ambassador-tls"}]}}

**Comment by tshauck** [comment] 2019-11-28 21:52
@knkski thanks for the response...

The output of the the get ingess command:

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      ingress.kubernetes.io/rewrite-target: ""
      ingress.kubernetes.io/ssl-passthrough: "false"
      ingress.kubernetes.io/ssl-redirect: "false"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"ambassador","namespace":"kubeflow"},"spec":{"tls":[{"hosts":["localhost"],"secretName":"ambassador-tls"}]}}
      kubernetes.io/ingress.allow-http: "false"
      kubernetes.io/ingress.class: nginx
    creationTimestamp: "2019-11-28T21:38:28Z"
    generation: 5
    labels:
      juju-controller-uuid: f7957347-4c03-42dc-8bc7-4920b7605993
      juju-model-uuid: 9fc33d74-abfd-488c-83e2-c27858204cae
    name: ambassador
    namespace: kubeflow
    resourceVersion: "99139"
    selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/ingresses/ambassador
    uid: aca579ad-a535-4bd5-999f-add373b266e1
  spec:
    rules:
    - host: localhost
      http:
        paths:
        - backend:
            serviceName: ambassador
            servicePort: 80
          path: /
    tls:
    - hosts:
      - localhost
      secretName: ambassador-tls
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

It looks like it does have a `tls` section from what I can tell. Manually patching with the second command returns the same things.

If helpful my port forward command and some output...

```
thauck@mmm:~$ microk8s.kubectl port-forward --address 0.0.0.0 -n kubeflow svc/ambassador 8080:80
Forwarding from 0.0.0.0:8080 -> 80
Handling connection for 8080
Handling connection for 8080
E1128 21:51:19.533905   20901 portforward.go:385] error copying from local connection to remote stream: read tcp4 172.16.0.12:8080->172.16.0.9:56972: read: connection reset by peer
56972: read: connection reset by peer
```

**Comment by knkski** [comment] 2019-12-10 17:53
@tshauck: You shouldn't need to run any port forwarding. After you've enabled Kubeflow, you should be able to just go to https://localhost/ to get to the dashboard. The Kubeflow dashboard requires HTTPS to be enabled, and all of the certificate handling happens inside of Kubernetes via Ingress resources.

**Comment by pgronau** [comment] 2020-01-29 17:38
I have the same issues.
curl on port 80 returns:
`user@machine:~$ curl -k https://192.168.178.51:80 -v` 

``` bash
* Rebuilt URL to: https://192.168.178.51:80/
*   Trying 192.168.178.51...
* TCP_NODELAY set
* Connected to 192.168.178.51 (192.168.178.51) port 80 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

**Comment by dkurt** [comment] 2020-02-07 19:15
Hi!

I way able to login to Kubeflow once following https://github.com/kubeflow/website/blob/master/content/docs/other-guides/virtual-dev/getting-started-multipass.md#install-kubeflow-using-microk8s but after machine reboot, https://localhost/kflogin reports `ERR_SSL_PROTOCOL_ERROR` in Chrome and `SSL_ERROR_INTERNAL_ERROR_ALERT` in Firefox

After reboot I just typed
```
$ microk8s.status --wait-ready

microk8s is running
addons:
cilium: disabled
dashboard: enabled
dns: enabled
fluentd: disabled
gpu: disabled
helm3: disabled
helm: disabled
ingress: enabled
istio: disabled
jaeger: disabled
juju: enabled
knative: disabled
kubeflow: enabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: enabled
registry: disabled
storage: enabled
```
Feel free to ask extra details which can help you.

**Comment by SamChb72** [comment] 2020-02-12 14:50
Hello,
Same error for me:

samy@cube:~$ curl -k -v https://10.104.38.12:80
* Rebuilt URL to: https://10.104.38.12:80/
*   Trying 10.104.38.12...
* TCP_NODELAY set
* Connected to 10.104.38.12 (10.104.38.12) port 80 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by knkski** [comment] 2020-02-12 16:46
@pgronau: The issue you're seeing is probably related to `https://192.168.178.51:80`, it's trying to use HTTPS on an HTTP port. Also, `microk8s.enable kubeflow` defaults to an external hostname of `localhost`, if you want to use a particular IP, you'll have to run `microk8s.kubectl edit -n kubeflow ingress/ambassador` and change `spec.rules[0].host` to the `<YOUR IP HERE>.xip.io` (the `.xip.io` is required due to Kubernetes not allowing straight IP addresses for ingresses). I'll open up a PR that will allow you to set the external hostname during `microk8s.enable kubeflow`.

**Comment by knkski** [comment] 2020-02-12 16:49
@dkurt: I believe I'm able to reproduce your issue. Doing `sudo snap stop microk8s && sudo snap start microk8s` (or probably also rebooting the host in your case) causes the ingress to lose the TLS section. Can you confirm this by pasting the output from `microk8s.kubectl get -n kubeflow ingress/ambassador -oyaml`? I'm investigating as to why that is.

**Comment by knkski** [comment] 2020-02-12 16:58
@SamChb72: The SSL error you're getting is from trying to talk HTTPS on an HTTP port. Does using `https://10.104.38.12` make the SSL error go away? You may still get a 404 not found error, in which case you'll have to edit `spec.rules[0].host` in `ingress/ambassador` to use `10.104.38.12.xip.io`

**Comment by SamChb72** [comment] 2020-02-13 11:09
Hello @knkski
Yes the SSL error went away then I could edit the host with 10.104.38.12.xip.io
but I still have the 404 not found
Here is the output yaml:

```
ubuntu@kubeflow-vm:~$ microk8s.kubectl get -n kubeflow ingress/ambassador -oyaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: ""
    ingress.kubernetes.io/ssl-passthrough: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{},"name":"ambassador","namespace":"kubeflow"},"spec":{"tls":[{"hosts":["localhost"],"secretName":"ambassador-tls"}]}}
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: nginx
  creationTimestamp: "2020-02-12T04:14:24Z"
  generation: 9
  labels:
    juju-controller-uuid: c8952d08-a134-443a-81d1-1c1095a65d2d
    juju-model-uuid: bd737eab-1767-4a24-8943-968f9e277d17
  name: ambassador
  namespace: kubeflow
  resourceVersion: "367922"
  selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/ingresses/ambassador
  uid: 93cc3eaa-3e0f-4c85-ac0e-2d05dfe10944
spec:
  rules:
  - host: 10.104.38.12.xip.io
    http:
      paths:
      - backend:
          serviceName: ambassador
          servicePort: 80
        path: /
  tls:
  - hosts:
    - localhost
    secretName: ambassador-tls
status:
  loadBalancer:
    ingress:
    - ip: 127.0.0.1
```

I also changed ambassador service type from ClusterIP to NodePort and revert it to ClusterIP, but same: 404 error.

**Comment by SamChb72** [comment] 2020-02-13 11:33
Hello @knkski, I replace localhost everywhere in the file and it worked :-)

**Comment by knkski** [comment] 2020-02-13 16:38
@dkurt: #965 should fix the issue that you're running into with cluster restart. Until that's merged and released, you can manually edit `ingress/ambassador` to add in a TLS section as shown here:

https://github.com/ubuntu/microk8s/blob/8ec87c8/microk8s-resources/actions/enable.kubeflow.sh

That will require that you edit it each time after you restart the cluster. Otherwise, you can copy `ingress/ambassador` under a different name, run `microk8s.juju unexpose ambassador`, and any edits you make to it will be persisted across reboots.

**Comment by knkski** [comment] 2020-02-13 16:40
@SamChb72: Good to hear! #965 will make `localhost` the default value, but allows setting a `KUBEFLOW_HOSTNAME` environment variable for `microk8s.enable kubeflow` that will override `localhost`.

**Comment by dkurt** [comment] 2020-02-13 16:52
@knkski, Thanks!

**Comment by ricpet** [comment] 2020-02-25 14:42
Hello, I am trying to change ``spec.rules[0].host`` but I get: 
```spec.rules[0].host: Invalid value: "192.168.XXX.XXXX": must be a DNS name, not an IP address```

**Comment by knkski** [comment] 2020-02-25 17:30
@ricpet: Yeah, that's a limitation of how Ingresses work, you'll need to use an address such as `192.168.xxx.xxx.xip.io`, which is a service that resolves DNS to the prefixed IP address contained in the URL.

**Comment by ricpet** [comment] 2020-02-25 18:00
@knkski thanks, you are right...I made the change but still no dashboard... should I re-enable kubeflow?

**Comment by knkski** [comment] 2020-02-25 21:18
@ricpet: How are you accessing the dashboard, and what error are you getting? And it won't hurt to re-enable kubeflow if you run into any issues

**Comment by ricpet** [comment] 2020-02-26 11:51
@knkski actually in the browser I was not adding `.xip.io` to the IP address of the machine. Now it works... thanks a lot for your help

**Comment by TomLaMantia** [comment] 2020-04-03 14:39
> @SamChb72: The SSL error you're getting is from trying to talk HTTPS on an HTTP port. Does using `https://10.104.38.12` make the SSL error go away? You may still get a 404 not found error, in which case you'll have to edit `spec.rules[0].host` in `ingress/ambassador` to use `10.104.38.12.xip.io`

@knkski After making these changes, do I need to restart microk8s or re-enable kubeflow? Additionally, if I am running microk8s with kubeflow enabled on a server via ssh from my workstation, do I need to do any additional port-forwarding to access the dashboard from my workstation? I am getting the same 404 issues presently. Thanks!

**Comment by knkski** [comment] 2020-04-06 15:17
@TomLaMantia: Kubeflow 1.0 came with the release of MicroK8s 1.18, and removes the need to manually edit ingresses. If you haven't yet updated, run `sudo snap refresh microk8s`. You may encounter issues with proxying the dashboard via SSH, the preferred method would be this:

    # First disable kubeflow if you have it enabled
    microk8s.disable kubeflow
    # Then, set the hostname to use when enabling kubeflow
    KUBEFLOW_HOSTNAME=my-other-machine's-hostname-here microk8s.enable kubeflow

For example, I have a beefy machine on my network with DNS set up as `foo.lan`, I SSH over to it and run `KUBEFLOW_HOSTNAME=foo.lan microk8s.enable kubeflow`, then access it via `foo.lan` in my browser.

**Comment by knkski** [comment] 2020-04-06 15:20
Marking this issue as complete since the original issue should be fixed

**Closed by knkski** 2020-04-06 15:20 UTC

**Comment by meta1paul** [comment] 2020-04-14 18:38
> access
I followed the steps indicated in enabling kubelow with microk8s (microk8s.enable kubeflow) without doing any previous customization as indicated on Kubeflow Web site where it is said :
